<?php

declare(strict_types=1);

namespace Podquilt\Tools\ContextSystem;

use JsonException;
use RuntimeException;

final readonly class ContextSystem
{
    private const GENERATED_MARKDOWN_NOTICE = '<!-- Generated by composer context:build. Do not edit by hand. -->';
    private const GENERATED_MERMAID_NOTICE = '<!-- Generated by composer context:build. Do not edit by hand. -->';
    private const PHPSTAN_IGNORE_TOKEN = '@phpstan' . '-ignore';

    /**
     * @var list<string>
     */
    private const BACKLOG_MARKERS = [
        'TO' . 'DO',
        'FIX' . 'ME',
        'HA' . 'CK',
        'X' . 'XX',
    ];

    /**
     * @var list<string>
     */
    private const WALK_IGNORES = [
        '.agent-context',
        '.git',
        '.phpstan',
        '.phpunit.cache',
        'logs',
        'media',
        'spec/generated',
        'vendor',
    ];

    public function __construct(
        private string $repoRoot,
        private PhpDependencyScanner $dependencyScanner = new PhpDependencyScanner(),
    ) {
    }

    public function loadContextData(): ContextData
    {
        $glossary = $this->loadJsonFile('glossary/terms.json');
        $subsystemIndex = $this->loadJsonFile('spec/subsystems/index.json');
        $subsystems = [];

        foreach ($this->listFiles('spec/subsystems') as $relativePath) {
            if (!str_ends_with($relativePath, '.json') || $relativePath === 'spec/subsystems/index.json') {
                continue;
            }

            $record = $this->loadJsonFile($relativePath);
            $record['filePath'] = $relativePath;
            $subsystems[] = $record;
        }

        usort(
            $subsystems,
            static fn (array $left, array $right): int => $left['id'] <=> $right['id'],
        );

        $decisionPaths = array_values(
            array_filter(
                $this->listFiles('spec/decisions'),
                static fn (string $relativePath): bool => str_ends_with($relativePath, '.md'),
            ),
        );
        sort($decisionPaths);

        $this->validateGlossary($glossary);
        $this->validateSubsystemIndex($subsystemIndex);
        $this->validateSubsystems($subsystems);

        return new ContextData(
            repoRoot: $this->repoRoot,
            glossary: $glossary,
            subsystemIndex: $subsystemIndex,
            subsystems: $subsystems,
            decisionPaths: $decisionPaths,
        );
    }

    /**
     * @return array{flags: array<string, string>, positionals: list<string>}
     */
    public static function parseArgs(array $argv): array
    {
        $flags = [];
        $positionals = [];

        foreach ($argv as $argument) {
            if (!str_starts_with($argument, '--')) {
                $positionals[] = $argument;
                continue;
            }

            $raw = substr($argument, 2);
            $parts = explode('=', $raw, 2);
            $flags[$parts[0]] = $parts[1] ?? 'true';
        }

        return [
            'flags' => $flags,
            'positionals' => $positionals,
        ];
    }

    /**
     * @return list<string>
     */
    public function writeContextArtifacts(ContextData $contextData): array
    {
        $outputs = $this->buildContextArtifacts($contextData);
        $changedFiles = [];

        foreach ($outputs as $relativePath => $contents) {
            if ($this->writeTextIfChanged($relativePath, $contents)) {
                $changedFiles[] = $relativePath;
            }
        }

        sort($changedFiles);

        return $changedFiles;
    }

    /**
     * @return array<string, string>
     */
    public function buildContextArtifacts(ContextData $contextData): array
    {
        $repoMap = $this->buildRepoMap($contextData);
        $this->assertOwnedCoverage($repoMap);

        return [
            'glossary/README.md' => $this->generateGlossaryReadme($contextData->glossary),
            'spec/generated/repo-map.json' => $this->encodeJson([
                'generatedBy' => 'composer context:build',
                'version' => 1,
                'files' => $repoMap['files'],
                'subsystems' => $repoMap['subsystems'],
            ]),
            'spec/generated/subsystem-graph.mmd' => $this->renderSubsystemGraph($contextData),
        ];
    }

    /**
     * @param list<string> $allowLocked
     * @return array<string, mixed>
     */
    public function buildTaskPacket(ContextData $contextData, string $task, array $allowLocked = []): array
    {
        $normalizedTask = trim($task);

        if ($normalizedTask === '') {
            throw new RuntimeException('A non-empty task description is required.');
        }

        $tokens = $this->tokenize($normalizedTask);
        $scoredSubsystems = [];

        foreach ($contextData->subsystems as $subsystem) {
            $scoredSubsystems[] = $this->scoreSubsystem(
                $subsystem,
                $contextData->glossary,
                $normalizedTask,
                $tokens,
            );
        }

        usort(
            $scoredSubsystems,
            static fn (array $left, array $right): int => $right['score'] <=> $left['score'] ?: ($left['subsystem']['id'] <=> $right['subsystem']['id']),
        );

        [$selectedIds, $expandedIds] = $this->expandSubsystemSelection(
            $scoredSubsystems,
            $contextData->subsystems,
        );
        $selectedSubsystems = array_values(
            array_filter(
                $contextData->subsystems,
                static fn (array $subsystem): bool => in_array($subsystem['id'], $expandedIds, true),
            ),
        );
        $lockedSubsystems = array_values(
            array_map(
                static fn (array $subsystem): string => $subsystem['id'],
                array_filter(
                    $selectedSubsystems,
                    static fn (array $subsystem): bool => $subsystem['status'] === 'locked',
                ),
            ),
        );
        sort($lockedSubsystems);

        $filteredAllowLocked = array_values(
            array_filter(
                array_unique($allowLocked),
                static fn (string $subsystemId): bool => in_array($subsystemId, $lockedSubsystems, true),
            ),
        );
        sort($filteredAllowLocked);

        $requiredSpecReads = ['spec/README.md'];
        $requiredDocsReads = [];
        $requiredDecisionReads = [];
        $requiredTests = [];
        $glossaryTerms = [];
        $requiredSubsystemRecords = [];

        foreach ($selectedSubsystems as $subsystem) {
            foreach ($subsystem['required_reads']['spec'] as $entry) {
                $requiredSpecReads[] = $entry;
            }

            foreach ($subsystem['required_reads']['docs'] as $entry) {
                $requiredDocsReads[] = $entry;
            }

            foreach ($subsystem['required_reads']['decisions'] as $entry) {
                $requiredDecisionReads[] = $entry;
            }

            foreach ($subsystem['tests'] as $entry) {
                $requiredTests[] = $entry;
            }

            foreach ($subsystem['glossary_terms'] as $entry) {
                $glossaryTerms[] = $entry;
            }

            $requiredSubsystemRecords[] = $subsystem['filePath'];
        }

        $matchedSubsystems = array_values(
            array_map(
                static fn (array $entry): array => [
                    'id' => $entry['subsystem']['id'],
                    'reasons' => $entry['reasons'],
                    'score' => $entry['score'],
                    'status' => $entry['subsystem']['status'],
                ],
                array_filter(
                    $scoredSubsystems,
                    static fn (array $entry): bool => $entry['score'] > 0,
                ),
            ),
        );

        return [
            'task' => $normalizedTask,
            'createdAt' => date(DATE_ATOM),
            'confidence' => $this->determineTaskConfidence($scoredSubsystems, $selectedIds),
            'matchedSubsystems' => $matchedSubsystems,
            'selectedSubsystemIds' => $selectedIds,
            'touchedSubsystemIds' => array_values(array_map(static fn (array $subsystem): string => $subsystem['id'], $selectedSubsystems)),
            'lockedSubsystems' => $lockedSubsystems,
            'allowLocked' => $filteredAllowLocked,
            'requiredSpecReads' => $this->uniqueSorted($requiredSpecReads),
            'requiredDocsReads' => $this->uniqueSorted($requiredDocsReads),
            'requiredDecisionReads' => $this->uniqueSorted($requiredDecisionReads),
            'requiredTests' => $this->uniqueSorted($requiredTests),
            'requiredSubsystemRecords' => $this->uniqueSorted($requiredSubsystemRecords),
            'glossaryTerms' => $this->uniqueSorted($glossaryTerms),
        ];
    }

    /**
     * @param array<string, mixed> $taskPacket
     */
    public function writeActiveTask(ContextData $contextData, array $taskPacket): void
    {
        $this->writeTextIfChanged(
            (string) $contextData->subsystemIndex['task_state_path'],
            $this->encodeJson($taskPacket),
        );
        $this->writeTextIfChanged(
            (string) $contextData->subsystemIndex['task_markdown_path'],
            $this->renderTaskMarkdown($taskPacket),
        );
    }

    /**
     * @return array{markdown: string, changedFiles: list<string>, touchedSubsystems: list<array<string, mixed>>}
     */
    public function buildReviewPacket(ContextData $contextData): array
    {
        $activeTask = $this->readActiveTask((string) $contextData->subsystemIndex['task_state_path']);

        if ($activeTask === null) {
            throw new RuntimeException('Cannot build a review packet without .agent-context/active-task.json. Run composer context:task first.');
        }

        $changedFiles = array_values(
            array_filter(
                $this->getGitStatus(),
                static fn (string $relativePath): bool => !str_starts_with($relativePath, '.agent-context/'),
            ),
        );
        $touchedSubsystemIds = $this->touchedSubsystemIdsForFiles($contextData, $changedFiles);
        $touchedSubsystems = array_values(
            array_filter(
                $contextData->subsystems,
                static fn (array $subsystem): bool => in_array($subsystem['id'], $touchedSubsystemIds, true),
            ),
        );
        $changedAuthoritativeArtifacts = array_values(
            array_filter(
                $changedFiles,
                static fn (string $relativePath): bool => str_starts_with($relativePath, 'spec/')
                    || str_starts_with($relativePath, 'docs/')
                    || str_starts_with($relativePath, 'glossary/')
                    || in_array($relativePath, ['README.md', 'AGENTS.md'], true),
            ),
        );

        $lines = [
            '# Drift Review Packet',
            '',
            'Task: ' . $activeTask['task'],
            'Confidence: ' . $activeTask['confidence'],
            '',
            '## Changed Files',
            '',
        ];

        foreach ($changedFiles as $entry) {
            $lines[] = '- ' . $entry;
        }

        $lines[] = '';
        $lines[] = '## Touched Subsystems';
        $lines[] = '';

        foreach ($touchedSubsystems as $subsystem) {
            $lines[] = '- ' . $subsystem['id'] . ' (' . $subsystem['status'] . ')';

            foreach ($subsystem['invariants'] as $invariant) {
                $lines[] = '  - ' . $invariant['id'] . ': ' . $invariant['statement'];
            }
        }

        $lines[] = '';
        $lines[] = '## Changed Authoritative Artifacts';
        $lines[] = '';

        foreach ($changedAuthoritativeArtifacts as $entry) {
            $lines[] = '- ' . $entry;
        }

        $lines[] = '';

        return [
            'markdown' => implode("\n", $lines),
            'changedFiles' => $changedFiles,
            'touchedSubsystems' => $touchedSubsystems,
        ];
    }

    public function writeReviewPacket(ContextData $contextData, string $markdown): void
    {
        $this->writeTextIfChanged(
            (string) $contextData->subsystemIndex['review_packet_path'],
            $markdown,
        );
    }

    public function checkContextState(ContextData $contextData): void
    {
        $staleArtifacts = $this->diffGeneratedArtifacts($contextData);

        if ($staleArtifacts !== []) {
            throw new RuntimeException(
                "Derived context artifacts are stale. Run composer context:build.\n" . $this->formatList($staleArtifacts),
            );
        }

        $changedFiles = array_values(
            array_filter(
                $this->getGitStatus(),
                fn (string $relativePath): bool => !$this->isLocalOutput($contextData, $relativePath)
                    && !$this->isDerivedArtifact($contextData, $relativePath),
            ),
        );

        if ($changedFiles === []) {
            return;
        }

        $activeTask = $this->readActiveTask((string) $contextData->subsystemIndex['task_state_path']);

        if ($activeTask === null) {
            throw new RuntimeException('Changed files detected without .agent-context/active-task.json. Run composer context:task -- "<task>" first.');
        }

        $this->checkTaskCoverage($contextData, $activeTask, $changedFiles);
    }

    public function checkTerminology(ContextData $contextData): void
    {
        $findings = [];

        foreach ($this->collectFirstPartyFiles($contextData) as $relativePath) {
            if (!$this->isTextCheckFile($relativePath) || $relativePath === 'glossary/terms.json' || $this->isDerivedArtifact($contextData, $relativePath)) {
                continue;
            }

            $contents = $this->readText($relativePath);
            $loweredContents = strtolower($contents);

            foreach ($contextData->glossary['terms'] as $term) {
                foreach ($term['discouraged'] as $discouragedValue) {
                    if (str_contains($loweredContents, strtolower((string) $discouragedValue))) {
                        $findings[] = sprintf(
                            '%s: discouraged term "%s" should be replaced with "%s".',
                            $relativePath,
                            $discouragedValue,
                            $term['canonical'],
                        );
                    }
                }
            }
        }

        if ($findings !== []) {
            throw new RuntimeException(implode("\n", $findings));
        }
    }

    public function checkComments(ContextData $contextData): void
    {
        $findings = [];

        foreach ($this->collectFirstPartyFiles($contextData) as $relativePath) {
            if (!$this->isTextCheckFile($relativePath) || $this->isDerivedArtifact($contextData, $relativePath)) {
                continue;
            }

            $contents = $this->readText($relativePath);
            $lines = explode("\n", $contents);
            $isMarkdown = str_ends_with($relativePath, '.md');
            $insideFence = false;

            foreach ($lines as $index => $line) {
                $lineForChecks = $this->lineForCommentChecks($line, $isMarkdown, $insideFence);

                if ($lineForChecks === null) {
                    continue;
                }

                if ($this->containsBacklogMarker($lineForChecks)) {
                    $findings[] = sprintf(
                        '%s:%d contains a backlog-style comment.',
                        $relativePath,
                        $index + 1,
                    );
                }

                if (
                    str_contains($lineForChecks, self::PHPSTAN_IGNORE_TOKEN)
                    && !preg_match(
                        '/' . preg_quote(self::PHPSTAN_IGNORE_TOKEN, '/') . '(?:-[a-z-]+)?\s+--\s+\S/',
                        $lineForChecks,
                    )
                ) {
                    $findings[] = sprintf(
                        '%s:%d contains an %s directive without a reason introduced by "--".',
                        $relativePath,
                        $index + 1,
                        self::PHPSTAN_IGNORE_TOKEN,
                    );
                }
            }
        }

        if ($findings !== []) {
            throw new RuntimeException(implode("\n", $findings));
        }
    }

    public function checkArchitecture(ContextData $contextData): void
    {
        $repoMap = $this->buildRepoMap($contextData);
        $findings = [];

        foreach ($contextData->subsystemIndex['architecture_rules'] as $rule) {
            foreach ($repoMap['files'] as $file) {
                if ($file['type'] !== 'code' || !PathMatcher::anyMatches($file['path'], $rule['from'])) {
                    continue;
                }

                foreach ($file['imports'] as $importPath) {
                    $isForbidden = PathMatcher::anyMatches($importPath, $rule['forbidden']);
                    $isAllowed = PathMatcher::anyMatches($importPath, $rule['allowed'] ?? []);
                    $isExcepted = false;

                    foreach ($rule['exceptions'] ?? [] as $exception) {
                        if (
                            PathMatcher::matches($file['path'], $exception['from'])
                            && PathMatcher::matches($importPath, $exception['to'])
                        ) {
                            $isExcepted = true;
                            break;
                        }
                    }

                    if ($isForbidden && !$isAllowed && !$isExcepted) {
                        $findings[] = sprintf(
                            "%s: %s -> %s\n  %s",
                            $rule['id'],
                            $file['path'],
                            $importPath,
                            $rule['message'],
                        );
                    }
                }
            }
        }

        if ($findings !== []) {
            throw new RuntimeException(implode("\n", $findings));
        }
    }

    public function formatBuildSummary(array $changedFiles): string
    {
        if ($changedFiles === []) {
            return 'Context artifacts already up to date.';
        }

        return "Updated context artifacts:\n" . $this->formatList($changedFiles);
    }

    /**
     * @param array<string, mixed> $taskPacket
     */
    public function formatTaskSummary(array $taskPacket): string
    {
        return rtrim($this->renderTaskMarkdown($taskPacket));
    }

    public function formatReviewSummary(string $reviewMarkdown): string
    {
        return rtrim($reviewMarkdown);
    }

    /**
     * @return array{files: list<array<string, mixed>>, subsystems: list<array<string, mixed>>}
     */
    private function buildRepoMap(ContextData $contextData): array
    {
        $firstPartyFiles = $this->collectFirstPartyFiles($contextData);
        $phpFiles = array_values(
            array_filter(
                $firstPartyFiles,
                fn (string $relativePath): bool => $this->isCodeFile($relativePath),
            ),
        );
        $importsByFile = $this->dependencyScanner->scan($this->repoRoot, $phpFiles);
        $dependentsByFile = [];

        foreach ($importsByFile as $filePath => $imports) {
            foreach ($imports as $importPath) {
                $dependentsByFile[$importPath][] = $filePath;
            }
        }

        $files = [];

        foreach ($firstPartyFiles as $relativePath) {
            $dependents = $dependentsByFile[$relativePath] ?? [];
            sort($dependents);
            $owners = array_values(
                array_map(
                    static fn (array $subsystem): string => $subsystem['id'],
                    $this->owningSubsystems($contextData, $relativePath),
                ),
            );

            $files[] = [
                'path' => $relativePath,
                'type' => $this->isCodeFile($relativePath) ? 'code' : 'text',
                'owners' => $owners,
                'imports' => $importsByFile[$relativePath] ?? [],
                'dependents' => array_values(array_unique($dependents)),
            ];
        }

        usort(
            $files,
            static fn (array $left, array $right): int => $left['path'] <=> $right['path'],
        );

        return [
            'files' => $files,
            'subsystems' => array_values(
                array_map(
                    static fn (array $subsystem): array => [
                        'id' => $subsystem['id'],
                        'status' => $subsystem['status'],
                        'owned_paths' => $subsystem['owned_paths'],
                        'related_paths' => $subsystem['related_paths'],
                        'depends_on' => $subsystem['depends_on'],
                        'used_by' => $subsystem['used_by'],
                    ],
                    $contextData->subsystems,
                ),
            ),
        ];
    }

    private function generateGlossaryReadme(array $glossary): string
    {
        $canonicalTermsById = [];

        foreach ($glossary['terms'] as $term) {
            $canonicalTermsById[$term['id']] = $term['canonical'];
        }

        $lines = [
            self::GENERATED_MARKDOWN_NOTICE,
            '',
            '# Project Glossary',
            '',
            'This directory is the authoritative source for project nomenclature. `../spec/README.md` defines implemented behavior. This glossary defines the exact words the project uses when describing that behavior.',
            '',
            '## Core Terms',
            '',
        ];

        foreach ($glossary['terms'] as $term) {
            $lines[] = '`' . $term['canonical'] . '`';
            $lines[] = '';
            $lines[] = '- ' . $term['definition'];
            $lines[] = '- Kind: `' . $term['kind'] . '`';
            $lines[] = '- Discouraged replacements:';

            foreach ($term['discouraged'] as $entry) {
                $lines[] = '  - ' . $entry;
            }

            $lines[] = '- Applies to:';

            foreach ($term['applies_to'] as $entry) {
                $lines[] = '  - `' . $entry . '`';
            }

            $relatedTerms = [];

            foreach ($term['related_terms'] as $relatedTermId) {
                $relatedTerms[] = '`' . ($canonicalTermsById[$relatedTermId] ?? $relatedTermId) . '`';
            }

            $lines[] = '- Related terms: ' . ($relatedTerms === [] ? 'none' : implode(', ', $relatedTerms));
            $lines[] = '';
        }

        $lines[] = '## Examples';
        $lines[] = '';
        $lines[] = '| Term | Example files or surfaces |';
        $lines[] = '| ---- | ------------------------ |';

        foreach ($glossary['examples'] as $entry) {
            $lines[] = sprintf(
                '| %s | %s |',
                $canonicalTermsById[$entry['term']] ?? $entry['term'],
                implode(', ', array_map(static fn (string $value): string => '`' . $value . '`', $entry['examples'])),
            );
        }

        $lines[] = '';
        $lines[] = '## Usage Rules';
        $lines[] = '';

        foreach ($glossary['usage_rules'] as $rule) {
            $lines[] = '- ' . $rule;
        }

        $lines[] = '';
        $lines[] = '## Cross References';
        $lines[] = '';

        foreach ($glossary['cross_references'] as $reference) {
            $lines[] = '- `' . $reference . '`';
        }

        $lines[] = '';

        return implode("\n", $lines);
    }

    private function renderSubsystemGraph(ContextData $contextData): string
    {
        $lines = [
            self::GENERATED_MERMAID_NOTICE,
            'flowchart TD',
        ];

        foreach ($contextData->subsystems as $subsystem) {
            $lines[] = sprintf(
                '  %s["%s (%s)"]',
                str_replace('-', '_', $subsystem['id']),
                $subsystem['title'],
                $subsystem['status'],
            );
        }

        foreach ($contextData->subsystems as $subsystem) {
            foreach ($subsystem['depends_on'] as $dependencyId) {
                $lines[] = sprintf(
                    '  %s --> %s',
                    str_replace('-', '_', $subsystem['id']),
                    str_replace('-', '_', $dependencyId),
                );
            }
        }

        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * @param array<string, mixed> $taskPacket
     */
    private function renderTaskMarkdown(array $taskPacket): string
    {
        $lines = [
            '# Active Task Brief',
            '',
            'Task: ' . $taskPacket['task'],
            'Confidence: ' . $taskPacket['confidence'],
            '',
            '## Matched Subsystems',
            '',
        ];

        foreach ($taskPacket['matchedSubsystems'] as $entry) {
            $lines[] = sprintf(
                '- %s (%s, score %d): %s',
                $entry['id'],
                $entry['status'],
                $entry['score'],
                implode(', ', $entry['reasons']),
            );
        }

        $lines[] = '';
        $lines[] = '## Required Reads';
        $lines[] = '';

        foreach ($taskPacket['requiredSpecReads'] as $entry) {
            $lines[] = '- ' . $entry;
        }

        foreach ($taskPacket['requiredDocsReads'] as $entry) {
            $lines[] = '- ' . $entry;
        }

        foreach ($taskPacket['requiredDecisionReads'] as $entry) {
            $lines[] = '- ' . $entry;
        }

        $lines[] = '';
        $lines[] = '## Locked Subsystems';
        $lines[] = '';

        if ($taskPacket['lockedSubsystems'] === []) {
            $lines[] = '- none';
        } else {
            foreach ($taskPacket['lockedSubsystems'] as $entry) {
                $lines[] = sprintf(
                    '- %s: %s',
                    $entry,
                    in_array($entry, $taskPacket['allowLocked'], true) ? 'allowed' : 'not allowed',
                );
            }
        }

        $lines[] = '';
        $lines[] = '## Required Tests';
        $lines[] = '';

        foreach ($taskPacket['requiredTests'] as $entry) {
            $lines[] = '- ' . $entry;
        }

        $lines[] = '';
        $lines[] = '## Glossary Terms';
        $lines[] = '';

        if ($taskPacket['glossaryTerms'] === []) {
            $lines[] = '- none';
        } else {
            foreach ($taskPacket['glossaryTerms'] as $entry) {
                $lines[] = '- ' . $entry;
            }
        }

        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * @param array<string, mixed> $activeTask
     * @param list<string> $changedFiles
     */
    private function checkTaskCoverage(ContextData $contextData, array $activeTask, array $changedFiles): void
    {
        $changedSubsystems = $this->touchedSubsystemIdsForFiles($contextData, $changedFiles);
        $unexpectedSubsystems = array_values(
            array_filter(
                $changedSubsystems,
                static fn (string $subsystemId): bool => !in_array($subsystemId, $activeTask['touchedSubsystemIds'], true),
            ),
        );

        if ($unexpectedSubsystems !== []) {
            throw new RuntimeException(
                "Changed files spill outside the active task packet:\n" . $this->formatList($unexpectedSubsystems),
            );
        }

        $disallowedLocked = [];

        foreach ($changedSubsystems as $subsystemId) {
            $subsystem = $this->findSubsystemById($contextData, $subsystemId);

            if ($subsystem !== null && $subsystem['status'] === 'locked' && !in_array($subsystemId, $activeTask['allowLocked'], true)) {
                $disallowedLocked[] = $subsystemId;
            }
        }

        if ($disallowedLocked !== []) {
            throw new RuntimeException(
                "Locked subsystem edits require explicit allow-list entries:\n" . $this->formatList($disallowedLocked),
            );
        }

        $changedSubsystemRecords = array_values(
            array_filter(
                $changedFiles,
                static fn (string $relativePath): bool => str_starts_with($relativePath, 'spec/subsystems/'),
            ),
        );
        $changedDecisions = array_values(
            array_filter(
                $changedFiles,
                static fn (string $relativePath): bool => str_starts_with($relativePath, 'spec/decisions/'),
            ),
        );
        $touchedOwnedSubsystems = $this->touchedOwnedSubsystemIdsForFiles(
            $contextData,
            array_values(
                array_filter(
                    $changedFiles,
                    fn (string $relativePath): bool => $this->requiresSubsystemRecordUpdate($relativePath),
                ),
            ),
        );

        foreach ($touchedOwnedSubsystems as $subsystemId) {
            $subsystem = $this->findSubsystemById($contextData, $subsystemId);

            if ($subsystem === null) {
                continue;
            }

            if (!in_array($subsystem['filePath'], $changedSubsystemRecords, true)) {
                throw new RuntimeException(
                    sprintf(
                        'Touched subsystem %s requires updating %s.',
                        $subsystemId,
                        $subsystem['filePath'],
                    ),
                );
            }

            if ($subsystem['status'] === 'locked' && $changedDecisions === []) {
                throw new RuntimeException(
                    sprintf(
                        'Touched locked subsystem %s requires an ADR change under spec/decisions/.',
                        $subsystemId,
                    ),
                );
            }
        }
    }

    /**
     * @param array<string, mixed> $subsystem
     * @param array<string, mixed> $glossary
     * @param list<string> $tokens
     * @return array{score: int, reasons: list<string>, subsystem: array<string, mixed>}
     */
    private function scoreSubsystem(array $subsystem, array $glossary, string $task, array $tokens): array
    {
        $score = 0;
        $reasons = [];
        $loweredTask = strtolower($task);
        $searchable = strtolower(
            implode(
                "\n",
                [
                    $subsystem['id'],
                    $subsystem['title'],
                    $subsystem['summary'],
                    implode("\n", array_map(static fn (array $entry): string => (string) $entry['name'], $subsystem['public_contracts'])),
                    implode("\n", array_map(static fn (array $entry): string => (string) $entry['statement'], $subsystem['invariants'])),
                    implode("\n", $subsystem['performance_constraints']),
                    implode("\n", $subsystem['glossary_terms']),
                ],
            ),
        );

        foreach ($tokens as $token) {
            if (str_contains(strtolower($subsystem['id']), $token)) {
                $score += 4;
                $reasons[] = 'id:' . $token;
                continue;
            }

            if (str_contains(strtolower($subsystem['title']), $token)) {
                $score += 4;
                $reasons[] = 'title:' . $token;
                continue;
            }

            if (str_contains($searchable, $token)) {
                $score += 1;
                $reasons[] = 'text:' . $token;
            }
        }

        foreach ($glossary['terms'] as $term) {
            if (!in_array($term['canonical'], $subsystem['glossary_terms'], true)) {
                continue;
            }

            if (str_contains($loweredTask, strtolower($term['canonical']))) {
                $score += 5;
                $reasons[] = 'glossary:' . $term['canonical'];
                continue;
            }

            foreach ($term['discouraged'] as $discouragedValue) {
                if (str_contains($loweredTask, strtolower((string) $discouragedValue))) {
                    $score += 3;
                    $reasons[] = 'glossary-discouraged:' . $term['canonical'];
                    break;
                }
            }
        }

        return [
            'score' => $score,
            'reasons' => $this->uniqueSorted($reasons),
            'subsystem' => $subsystem,
        ];
    }

    /**
     * @param list<array{score: int, reasons: list<string>, subsystem: array<string, mixed>}> $scoredSubsystems
     * @param list<array<string, mixed>> $allSubsystems
     * @return array{0: list<string>, 1: list<string>}
     */
    private function expandSubsystemSelection(array $scoredSubsystems, array $allSubsystems): array
    {
        $selectedIds = [];

        foreach ($scoredSubsystems as $entry) {
            if ($entry['score'] > 0) {
                $selectedIds[] = $entry['subsystem']['id'];
            }
        }

        $selectedIds = array_values(array_unique($selectedIds));
        $expandedIds = $selectedIds;
        $queue = $selectedIds;

        while ($queue !== []) {
            $currentId = array_shift($queue);

            foreach ($allSubsystems as $subsystem) {
                if ($subsystem['id'] !== $currentId) {
                    continue;
                }

                foreach (array_merge($subsystem['depends_on'], $subsystem['used_by']) as $relatedId) {
                    if (!in_array($relatedId, $expandedIds, true)) {
                        $expandedIds[] = $relatedId;
                        $queue[] = $relatedId;
                    }
                }
            }
        }

        if ($expandedIds !== [] && !in_array('repo-governance-context-system', $expandedIds, true)) {
            $expandedIds[] = 'repo-governance-context-system';
        }

        sort($selectedIds);
        sort($expandedIds);

        return [$selectedIds, $expandedIds];
    }

    /**
     * @param list<array{score: int, reasons: list<string>, subsystem: array<string, mixed>}> $scoredSubsystems
     * @param list<string> $selectedIds
     */
    private function determineTaskConfidence(array $scoredSubsystems, array $selectedIds): string
    {
        if ($selectedIds === []) {
            return 'low';
        }

        $positiveScores = array_values(
            array_map(
                static fn (array $entry): int => $entry['score'],
                array_filter(
                    $scoredSubsystems,
                    static fn (array $entry): bool => $entry['score'] > 0,
                ),
            ),
        );
        $topScore = $positiveScores[0] ?? 0;
        $secondScore = $positiveScores[1] ?? 0;

        if ($topScore >= 6 && $topScore > $secondScore) {
            return 'high';
        }

        return 'medium';
    }

    /**
     * @return list<string>
     */
    private function collectFirstPartyFiles(ContextData $contextData): array
    {
        $files = [];

        foreach ($contextData->subsystemIndex['source_roots'] as $rootEntry) {
            foreach ($this->listFiles((string) $rootEntry) as $relativePath) {
                if (
                    in_array($relativePath, $contextData->subsystemIndex['exempt_paths'], true)
                    || $this->isGeneratedRoot($contextData, $relativePath)
                ) {
                    continue;
                }

                $files[$relativePath] = true;
            }
        }

        $paths = array_keys($files);
        sort($paths);

        return $paths;
    }

    /**
     * @return list<string>
     */
    private function listFiles(string $relativePath): array
    {
        $normalizedPath = PathMatcher::normalize($relativePath);
        $absolutePath = $this->absolutePath($normalizedPath);

        if (!file_exists($absolutePath)) {
            return [];
        }

        if (is_file($absolutePath)) {
            return [$normalizedPath];
        }

        $results = [];
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($absolutePath, \FilesystemIterator::SKIP_DOTS),
        );

        foreach ($iterator as $entry) {
            $entryPath = PathMatcher::normalize(substr($entry->getPathname(), strlen($this->repoRoot) + 1));

            foreach (self::WALK_IGNORES as $ignoredPath) {
                if (PathMatcher::isWithin($entryPath, $ignoredPath)) {
                    continue 2;
                }
            }

            if ($entry->isFile()) {
                $results[] = $entryPath;
            }
        }

        sort($results);

        return $results;
    }

    /**
     * @param array{files: list<array<string, mixed>>, subsystems: list<array<string, mixed>>} $repoMap
     */
    private function assertOwnedCoverage(array $repoMap): void
    {
        $unmappedFiles = array_values(
            array_map(
                static fn (array $file): string => $file['path'],
                array_filter(
                    $repoMap['files'],
                    static fn (array $file): bool => $file['owners'] === [],
                ),
            ),
        );

        if ($unmappedFiles !== []) {
            throw new RuntimeException(
                "Unmapped first-party files detected:\n" . $this->formatList($unmappedFiles),
            );
        }
    }

    /**
     * @return list<string>
     */
    private function diffGeneratedArtifacts(ContextData $contextData): array
    {
        $outputs = $this->buildContextArtifacts($contextData);
        $stale = [];

        foreach ($outputs as $relativePath => $contents) {
            if (!file_exists($this->absolutePath($relativePath)) || $this->readText($relativePath) !== $contents) {
                $stale[] = $relativePath;
            }
        }

        sort($stale);

        return $stale;
    }

    /**
     * @return list<string>
     */
    private function getGitStatus(): array
    {
        $output = $this->runCommand(['git', 'status', '--short', '--untracked-files=all']);
        $paths = [];

        foreach (explode("\n", rtrim($output, "\r\n")) as $line) {
            if ($line === '') {
                continue;
            }

            $paths[] = PathMatcher::normalize(substr($line, 3));
        }

        sort($paths);

        return $paths;
    }

    /**
     * @return array<string, mixed>|null
     */
    private function readActiveTask(string $relativePath): ?array
    {
        $absolutePath = $this->absolutePath($relativePath);

        if (!file_exists($absolutePath)) {
            return null;
        }

        /** @var array<string, mixed> $decoded */
        $decoded = $this->decodeJson((string) file_get_contents($absolutePath), $relativePath);

        return $decoded;
    }

    /**
     * @return list<string>
     */
    private function touchedSubsystemIdsForFiles(ContextData $contextData, array $filePaths): array
    {
        $subsystemIds = [];

        foreach ($filePaths as $relativePath) {
            foreach ($contextData->subsystems as $subsystem) {
                if (
                    PathMatcher::anyMatches($relativePath, $subsystem['owned_paths'])
                    || PathMatcher::anyMatches($relativePath, $subsystem['related_paths'])
                ) {
                    $subsystemIds[] = $subsystem['id'];
                }
            }
        }

        return $this->uniqueSorted($subsystemIds);
    }

    /**
     * @return list<string>
     */
    private function touchedOwnedSubsystemIdsForFiles(ContextData $contextData, array $filePaths): array
    {
        $subsystemIds = [];

        foreach ($filePaths as $relativePath) {
            foreach ($this->owningSubsystems($contextData, $relativePath) as $subsystem) {
                $subsystemIds[] = $subsystem['id'];
            }
        }

        return $this->uniqueSorted($subsystemIds);
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function owningSubsystems(ContextData $contextData, string $relativePath): array
    {
        return array_values(
            array_filter(
                $contextData->subsystems,
                static fn (array $subsystem): bool => PathMatcher::anyMatches($relativePath, $subsystem['owned_paths']),
            ),
        );
    }

    /**
     * @return array<string, mixed>|null
     */
    private function findSubsystemById(ContextData $contextData, string $subsystemId): ?array
    {
        foreach ($contextData->subsystems as $subsystem) {
            if ($subsystem['id'] === $subsystemId) {
                return $subsystem;
            }
        }

        return null;
    }

    private function isCodeFile(string $relativePath): bool
    {
        return str_ends_with($relativePath, '.php');
    }

    private function isTextCheckFile(string $relativePath): bool
    {
        return str_ends_with($relativePath, '.php')
            || str_ends_with($relativePath, '.md')
            || str_ends_with($relativePath, '.json');
    }

    private function isGeneratedRoot(ContextData $contextData, string $relativePath): bool
    {
        foreach ($contextData->subsystemIndex['generated_roots'] as $rootPath) {
            if (PathMatcher::isWithin($relativePath, $rootPath)) {
                return true;
            }
        }

        return false;
    }

    private function isLocalOutput(ContextData $contextData, string $relativePath): bool
    {
        foreach ($contextData->subsystemIndex['allowed_local_outputs'] as $rootPath) {
            if (PathMatcher::isWithin($relativePath, $rootPath)) {
                return true;
            }
        }

        return false;
    }

    private function isDerivedArtifact(ContextData $contextData, string $relativePath): bool
    {
        return $relativePath === 'glossary/README.md' || $this->isGeneratedRoot($contextData, $relativePath);
    }

    private function requiresSubsystemRecordUpdate(string $relativePath): bool
    {
        return str_starts_with($relativePath, 'src/')
            || str_starts_with($relativePath, 'tests/')
            || str_starts_with($relativePath, 'tools/')
            || in_array(
                $relativePath,
                [
                    '.dockerignore',
                    '.gitignore',
                    '.htaccess',
                    'AGENTS.md',
                    'Dockerfile',
                    'README.md',
                    'compose.yaml',
                    'composer.json',
                    'composer.lock',
                    'config.json.example',
                    'index.php',
                    'phpstan.neon',
                    'phpunit.xml',
                    '.php-cs-fixer.dist.php',
                ],
                true,
            )
            || str_starts_with($relativePath, '.github/');
    }

    private function containsBacklogMarker(string $line): bool
    {
        $pattern = '/\b(' . implode('|', array_map('preg_quote', self::BACKLOG_MARKERS)) . ')\b/';

        return preg_match($pattern, $line) === 1;
    }

    private function lineForCommentChecks(string $line, bool $isMarkdown, bool &$insideFence): ?string
    {
        if (!$isMarkdown) {
            return $line;
        }

        if (preg_match('/^\s*```/', $line) === 1) {
            $insideFence = !$insideFence;

            return null;
        }

        if ($insideFence) {
            return null;
        }

        return preg_replace('/`[^`]*`/', '', $line) ?? $line;
    }

    /**
     * @param array<string, mixed> $glossary
     */
    private function validateGlossary(array $glossary): void
    {
        foreach (['terms', 'examples', 'usage_rules', 'cross_references'] as $field) {
            if (!isset($glossary[$field]) || !is_array($glossary[$field])) {
                throw new RuntimeException('glossary/terms.json must define ' . $field . '.');
            }
        }
    }

    /**
     * @param array<string, mixed> $subsystemIndex
     */
    private function validateSubsystemIndex(array $subsystemIndex): void
    {
        foreach ([
            'source_roots',
            'generated_roots',
            'allowed_local_outputs',
            'exempt_paths',
            'architecture_rules',
            'task_state_path',
            'task_markdown_path',
            'review_packet_path',
        ] as $field) {
            if (!array_key_exists($field, $subsystemIndex)) {
                throw new RuntimeException('spec/subsystems/index.json must define ' . $field . '.');
            }
        }
    }

    /**
     * @param list<array<string, mixed>> $subsystems
     */
    private function validateSubsystems(array $subsystems): void
    {
        $ids = [];

        foreach ($subsystems as $subsystem) {
            foreach ([
                'id',
                'title',
                'status',
                'summary',
                'owned_paths',
                'related_paths',
                'entrypoints',
                'depends_on',
                'used_by',
                'required_reads',
                'glossary_terms',
                'public_contracts',
                'invariants',
                'performance_constraints',
                'change_policy',
                'tests',
                'decision_refs',
                'history_anchors',
            ] as $field) {
                if (!array_key_exists($field, $subsystem)) {
                    throw new RuntimeException(sprintf('%s is missing %s.', $subsystem['filePath'] ?? 'subsystem record', $field));
                }
            }

            $ids[] = $subsystem['id'];
        }

        foreach ($subsystems as $subsystem) {
            foreach (array_merge($subsystem['depends_on'], $subsystem['used_by']) as $dependencyId) {
                if (!in_array($dependencyId, $ids, true)) {
                    throw new RuntimeException(sprintf('%s references unknown subsystem %s.', $subsystem['filePath'], $dependencyId));
                }
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    private function loadJsonFile(string $relativePath): array
    {
        return $this->decodeJson($this->readText($relativePath), $relativePath);
    }

    /**
     * @return array<string, mixed>
     */
    private function decodeJson(string $contents, string $relativePath): array
    {
        try {
            $decoded = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        } catch (JsonException $exception) {
            throw new RuntimeException(sprintf('Unable to parse %s: %s', $relativePath, $exception->getMessage()), 0, $exception);
        }

        if (!is_array($decoded) || array_is_list($decoded)) {
            throw new RuntimeException($relativePath . ' must decode to an object.');
        }

        return $decoded;
    }

    private function readText(string $relativePath): string
    {
        $contents = file_get_contents($this->absolutePath($relativePath));

        if ($contents === false) {
            throw new RuntimeException('Unable to read ' . $relativePath . '.');
        }

        return $contents;
    }

    private function writeTextIfChanged(string $relativePath, string $contents): bool
    {
        $absolutePath = $this->absolutePath($relativePath);
        $directory = dirname($absolutePath);

        if (!is_dir($directory) && !mkdir($directory, 0777, true) && !is_dir($directory)) {
            throw new RuntimeException('Unable to create directory for ' . $relativePath . '.');
        }

        if (file_exists($absolutePath) && file_get_contents($absolutePath) === $contents) {
            return false;
        }

        file_put_contents($absolutePath, $contents);

        return true;
    }

    private function absolutePath(string $relativePath): string
    {
        return $this->repoRoot . DIRECTORY_SEPARATOR . PathMatcher::normalize($relativePath);
    }

    /**
     * @return list<string>
     */
    private function uniqueSorted(array $values): array
    {
        $uniqueValues = array_values(array_unique($values));
        sort($uniqueValues);

        return $uniqueValues;
    }

    /**
     * @return list<string>
     */
    private function tokenize(string $input): array
    {
        $normalized = preg_replace('/[^a-z0-9]+/i', ' ', strtolower($input)) ?? '';
        $tokens = array_values(
            array_filter(
                preg_split('/\s+/', trim($normalized)) ?: [],
                static fn (string $token): bool => strlen($token) >= 3,
            ),
        );

        return $this->uniqueSorted($tokens);
    }

    /**
     * @param list<string> $values
     */
    private function formatList(array $values): string
    {
        return implode("\n", array_map(static fn (string $value): string => '- ' . $value, $values));
    }

    /**
     * @param array<string, mixed> $value
     */
    private function encodeJson(array $value): string
    {
        try {
            return json_encode($value, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR) . "\n";
        } catch (JsonException $exception) {
            throw new RuntimeException('Unable to encode JSON output.', 0, $exception);
        }
    }

    /**
     * @param list<string> $command
     */
    private function runCommand(array $command): string
    {
        $escaped = implode(' ', array_map('escapeshellarg', $command));
        $output = shell_exec('cd ' . escapeshellarg($this->repoRoot) . ' && ' . $escaped);

        if (!is_string($output)) {
            throw new RuntimeException('Command failed: ' . implode(' ', $command));
        }

        return $output;
    }
}
